
dist: trusty
sudo: false

language: node_js
node_js:
  - '10'

cache:
  directories:
    - ./node_modules

install:
  - mkdir temp
  - cd temp
  - git clone https://github.com/marcobuschini/parking-widget.git
  - cd parking-widget
  - npm install
  - ng build widget
  - cd ../..
  - sudo chown -R $USER node_modules/widget
  - npm install

script:
  - ng test --coverage  --coverageReporters=text-lcov | node node_modules/coveralls/bin/coveralls.js
